### ISSUE TITLE
Crash with navigation

### ISSUE THREAD

**Issue by SamiuZhong** [Zhuinden/ViewBindingExample#3]
I use navigation to destination from A fragment to B fragment, it's OK.

But when I jump back A fragment from B fragment, it crashed. 

This is my demo [WanAndroid_Gank](https://github.com/SamiuZhong/WanAndroid_Gank)
It's in branch "material", commit "TODO FixViewBindingDelegate"
Bug occur between WanHomeFragment and BrowserFragment

This is error information
```
    java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
        at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:328)
        at com.samiu.base.ui.FragmentViewBindingDelegate.getValue(ViewBindingDelegate.kt:59)
        at com.samiu.host.ui.base.nav.BrowserFragment.getBinding(Unknown Source:10)
        at com.samiu.host.ui.base.nav.BrowserFragment.access$getBinding$p(BrowserFragment.kt:20)
        at com.samiu.host.ui.base.nav.BrowserFragment$initWebView$$inlined$run$lambda$2.onProgressChanged(BrowserFragment.kt:52)
        at com.tencent.smtt.sdk.f.onProgressChanged(SmttWebChromeClient.java:182)
        at com.tencent.tbs.core.webkit.tencent.TencentWebChromeClient.onProgressChanged(TbsJavaCore:46)
        at android.webview.chromium.WebViewContentsClientAdapter.onProgressChanged(TbsJavaCore:263)
        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(TbsJavaCore:231)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

Thaks very much

**Comment by Zhuinden** [comment]
Hi, thank you for the interesting question!

If you try to debug the code, you'll see that ***it doesn't crash at all***. If you DON'T debug the code, you see that ***it crashes all the time***.

Conclusion: multi-threading bug.

WebViews run on their own thread, and apparently they run at strange times. I could fix your sample by creating a `val binding = binding` in `onViewCreated` which is then accessed by the `webChromeClient`.

``` kotlin
    private fun initWebView() {
        val binding = binding // <--
        
        binding.progressBar.progressDrawable =
            getDrawable(requireContext(), R.drawable.color_progressbar)
        binding.webView.run {
            webViewClient = object : WebViewClient() {

                override fun onPageStarted(p0: WebView?, p1: String?, p2: Bitmap?) {
                    super.onPageStarted(p0, p1, p2)
                    binding.progressBar.visibility = View.VISIBLE
                }

                override fun onPageFinished(p0: WebView?, p1: String?) {
                    super.onPageFinished(p0, p1)
                    binding.progressBar.visibility = View.GONE
                }
            }
            webChromeClient = object : WebChromeClient() {
                override fun onProgressChanged(p0: WebView?, p1: Int) {
                    super.onProgressChanged(p0, p1)
                    binding.progressBar.progress = p1
                }
            }
        }
    }
```

**Comment by SamiuZhong** [comment]
__Fantastic!__ 

Thank you most sincerely not only the bug fixed but also you spend time for my demo even read my code, you are so friendly an enthusiastic.

Thanks again, and I'll keep following you.
