### ISSUE TITLE
FragmentViewBindingDelegate does play nice with dialog fragments

### ISSUE THREAD

**Issue by iamarjun** [Zhuinden/ViewBindingExample#5]
For some reason, FragmentViewBindingDelegate doesn't play nice with dialog fragments, it seems like that binding is getting initialized every time the dialog fragment is invoked.

You can replicate the issue by checking out to this commit and building the project and attempting to invoke the location bottom sheet by clicking on the location icon on the toolbar: https://github.com/iamarjun/News/commit/432a2df7abb582fc09c83722116c62e1870a3fb0

Steps to replicate:
1. Start the app, click the location icon on the toolbar, the bottom sheet invokes without any problem.
2. Repeat the same thing again..
3. Do the same thing again and this time the bottom sheet would be empty.

I hope I'm not missing something or using it correctly.

**Comment by Zhuinden** [comment]
I can't repro this, but I got this:

```
10-21 22:15:22.117 18953-18953/com.example.news E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.news, PID: 18953
    java.lang.IllegalStateException: Fragment already added: LocationDialogFragment{21fdedb} (a9dfba3a-d65c-48c3-8924-25e83a336f1e) dialog}
        at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:67)
        at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1577)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:405)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

which seems to be caused by not checking if a Fragment is added before adding it back.

In fact, this is only possible if the fragment instance is retained at field level, rather than a new one being created.

In fact...

``` kotlin
    private val bottomSheet: LocationDialogFragment by lazy { LocationDialogFragment.newInstance() }
```

Conclusion: the problem is not with the `binding`, but with the asynchronous nature of fragment transactions, and a dialog fragment being retained as a field.

As per [issue #2](https://proandroiddev.com/the-seven-actually-10-cardinal-sins-of-android-development-491d2f64c8e0), this is not recommended. Create a new instance of the DialogFragment instead making a lazy one.

**Comment by Zhuinden** [comment]
If my analysis was incorrect, feel free to comment 😊

**Comment by iamarjun** [comment]
Oh, I've been making sins all this time, thanks for the article, it clearly explains my problem.
